require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IntroTextsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # IntroText. As you add validations to IntroText, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IntroTextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all intro_texts as @intro_texts" do
      intro_text = IntroText.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:intro_texts)).to eq([intro_text])
    end
  end

  describe "GET show" do
    it "assigns the requested intro_text as @intro_text" do
      intro_text = IntroText.create! valid_attributes
      get :show, {:id => intro_text.to_param}, valid_session
      expect(assigns(:intro_text)).to eq(intro_text)
    end
  end

  describe "GET new" do
    it "assigns a new intro_text as @intro_text" do
      get :new, {}, valid_session
      expect(assigns(:intro_text)).to be_a_new(IntroText)
    end
  end

  describe "GET edit" do
    it "assigns the requested intro_text as @intro_text" do
      intro_text = IntroText.create! valid_attributes
      get :edit, {:id => intro_text.to_param}, valid_session
      expect(assigns(:intro_text)).to eq(intro_text)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IntroText" do
        expect {
          post :create, {:intro_text => valid_attributes}, valid_session
        }.to change(IntroText, :count).by(1)
      end

      it "assigns a newly created intro_text as @intro_text" do
        post :create, {:intro_text => valid_attributes}, valid_session
        expect(assigns(:intro_text)).to be_a(IntroText)
        expect(assigns(:intro_text)).to be_persisted
      end

      it "redirects to the created intro_text" do
        post :create, {:intro_text => valid_attributes}, valid_session
        expect(response).to redirect_to(IntroText.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved intro_text as @intro_text" do
        post :create, {:intro_text => invalid_attributes}, valid_session
        expect(assigns(:intro_text)).to be_a_new(IntroText)
      end

      it "re-renders the 'new' template" do
        post :create, {:intro_text => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested intro_text" do
        intro_text = IntroText.create! valid_attributes
        put :update, {:id => intro_text.to_param, :intro_text => new_attributes}, valid_session
        intro_text.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested intro_text as @intro_text" do
        intro_text = IntroText.create! valid_attributes
        put :update, {:id => intro_text.to_param, :intro_text => valid_attributes}, valid_session
        expect(assigns(:intro_text)).to eq(intro_text)
      end

      it "redirects to the intro_text" do
        intro_text = IntroText.create! valid_attributes
        put :update, {:id => intro_text.to_param, :intro_text => valid_attributes}, valid_session
        expect(response).to redirect_to(intro_text)
      end
    end

    describe "with invalid params" do
      it "assigns the intro_text as @intro_text" do
        intro_text = IntroText.create! valid_attributes
        put :update, {:id => intro_text.to_param, :intro_text => invalid_attributes}, valid_session
        expect(assigns(:intro_text)).to eq(intro_text)
      end

      it "re-renders the 'edit' template" do
        intro_text = IntroText.create! valid_attributes
        put :update, {:id => intro_text.to_param, :intro_text => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested intro_text" do
      intro_text = IntroText.create! valid_attributes
      expect {
        delete :destroy, {:id => intro_text.to_param}, valid_session
      }.to change(IntroText, :count).by(-1)
    end

    it "redirects to the intro_texts list" do
      intro_text = IntroText.create! valid_attributes
      delete :destroy, {:id => intro_text.to_param}, valid_session
      expect(response).to redirect_to(intro_texts_url)
    end
  end

end
